### ISSUE TITLE
cannot specify dbrp in implicitly and explicitly

### ISSUE THREAD

**Issue by hellmanj** [gpestana/kapacitor-unit#21]
Hi, was very excited to try this framework but I'm having a problem I don't understand.  I have tried removing db/rp from yaml as well as removing it from tick script (not allowed) but neither seems to help.  Any ideas?

```
$ kapacitor-unit --dir etc/kapacitor/load/tasks --tests tests/test_cleanup_nomad.yaml 
...
The unit test framework for TICK scripts (v0.8)

ts=2018-04-17T19:51:02.850Z lvl=info msg="http request" service=http host=127.0.0.1 username=- start=2018-04-17T19:51:02.834445448Z method=POST uri=/kapacitor/v1/tasks protocol=HTTP/1.1 status=400 referer=- user-agent=Go-http-client/1.1 request-id=a8aeea8f-4278-11e8-800d-000000000000 duration=16.322373ms
2018/04/17 19:51:02 400 Bad Request:: {
    "error": "cannot specify dbrp in both implicitly and explicitly"
}
```

tick script:
```
dbrp "nomad"."one_month"

var allocated = stream
    |from()
        .measurement('nomad_node_allocated_cpu_megahertz')
    |groupBy('tg_region')
    |window()
        .period(30s)
        .every(30s)
    |mean('gauge')
    |sum('mean')

var capacity = stream
    |from()
        .measurement('nomad_node_resource_cpu_megahertz')
    |groupBy('tg_region')
    |window()
        .period(30s)
        .every(30s)
    |mean('total')
    |sum('mean')

allocated
    |join(capacity)
        .as('allocated', 'capacity')
    |eval(lambda: ("allocated.sum" / "allocated.sum") * 100)
        // Give the resulting field a name
        .as('perc_allocated')
    |log()
    |httpOut('nomad_perc_allocated')
    |alert()
        .id('{{ .Name }}/{{ index .Tags "tg_region" }}')
        .message('{{ .ID }} is {{ .Level }} CPU allocation/capacity rate for {{ index .Tags "tg_region" }}: {{ index .Fields "perc_allocated" | printf "%0.2f" }}%')
        .crit(lambda: "sum" > 80)
```
test yaml:
```yaml
tests:
  - name: "Alert allocation approaching capacity:: crit"
    description: "Task should trigger Critical when allocated/capacity above 80"
    task_name: "cleanup_nomad.tick"
    db: "nomad"
    rp: "one_month"
    type: "stream"
    data:
      - "nomad_node_allocated_cpu_megahertz,tg_region=test_region gauge=9000"
      - "nomad_node_resource_cpu_megahertz,tg_region=test_region gauge=10000"
    expects:
      ok: 0
      warn: 0
      crit: 1
```
